name: Deploy to Firebase Hosting prod
"on":
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install && npm run build --production --aot --output-hashing=all
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          args: -P dev deploy --only hosting
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_OPEN_BANKING_SITIO_PUBLICO }}"
          channelId: live
          projectId: open-banking-sitio-publico
